### ISSUE TITLE
Confusing actual clojure.test result when comparing sets

### ISSUE THREAD

**Issue by eerohele** [BetterThanTomorrow/calva#1156] opened 2021-04-27 17:16 UTC
Running this test in Calva:

```clojure
(deftest foo
  (is (= #{1 2 3} #{1 2 4})))
```

Prints a result like this:

```clojure
; FAIL in my.ns/foo (ns.clj:42):
; expected:
#{1 3 2}
; actual:
(#{1 4 2})
```

Note the confusing extra parens around the actual result.

As discussed on Slack, this might be an upstream issue (maybe cider-nrepl).

**Comment by bpringe** [comment] 2021-04-28 01:07
Thanks for the report! This is a duplicate of https://github.com/BetterThanTomorrow/calva/issues/794. Let's continue to track it there.

**Closed as completed by bpringe** 2021-04-28 01:07 UTC
