### ISSUE TITLE
Linting failing

### ISSUE THREAD

**Issue by WhoNeedszZz** [BetterThanTomorrow/calva#36] opened 2018-05-11 09:53 UTC
Something has broken linting. Joker recently updated to 0.9.2 so it could be the culprit, but the update didn't include anything major.

Trace:
`TypeError: Cannot read property 'getDocument' of undefined
	at Object.lintDocument$$module$calva$repl$middleware$lint [as lintDocument]`

**Comment by PEZ** [comment] 2018-05-11 20:43
I found the bug. It had to do with our porting the extension to ClojureScript. We had forgotten to fix an import in `lint.js`.

Many thanks for reporting! Please test the latest version of Calva and see if it really is fixed for you. If so, please close this issue.

**Comment by WhoNeedszZz** [comment] 2018-05-11 21:27
No, it is still broken. There is another error now. `TypeError: module$calva$state.deref is not a function
	at Object.lintDocument$$module$calva$repl$middleware$lint [as lintDocument]`

I see you are using git in a rather unorthodox way. I see you referenced the issue in two commits, but a pull request should reference the issue and that PR reviewed by someone else (which I can help with). With a verified and *tested* review that pull request completing should close the issue; not a person deciding arbitrarily.

**Comment by mrkaspa** [comment] 2018-05-11 23:19
I have this setting and also does not work also have joker installed

"calva.lintOnSave": true

**Comment by WhoNeedszZz** [comment] 2018-05-12 02:12
I'm in the process of fixing this. Just about done and will have a PR ready.

**Comment by pedrorgirardi** [comment] 2018-05-12 02:14
Hi @WhoNeedszZz, thank you, but it looks like @PEZ already did it and a new Calva version was published.

**Comment by WhoNeedszZz** [comment] 2018-05-12 04:06
@pedrorgirardi, no the commit he pushed did not fix it.

**Comment by WhoNeedszZz** [comment] 2018-05-12 04:11
On top of this the changes to nrepl.js to nrepl.cljs is breaking nrepl functionality. I'm trying to fix both while I'm at it.

**Comment by pedrorgirardi** [comment] 2018-05-12 04:39
@WhoNeedszZz alright then! 😀

Do you know what is broken with `nrepl.cljs`?

**Comment by WhoNeedszZz** [comment] 2018-05-12 04:41
Unfortunately, I don't. It's more difficult to figure out for me since I wasn't familiar with the code before the change happened. I'm navigating back through the commit log, but having difficulty with that since many of the commits were committed directly to master instead of a feature branch and then merged when tested and ready.

**Comment by WhoNeedszZz** [comment] 2018-05-12 04:42
The good news is that I've fixed the linting problem and the imports are now correct. Getting a PR ready.

**Comment by pedrorgirardi** [comment] 2018-05-12 04:45
Cool! The `nrepl.cljs` was done on a separate branch and merged into `master` later on and this is the PR #33 if you want to take a look.

**Comment by WhoNeedszZz** [comment] 2018-05-12 05:14
Right, I can see all of that. My point was that due to things being converted in pieces there is added fragmentation to the code and is hindering understanding of the code base for someone new. It is generally advisable to be an ongoing effort in a separate branch that merges with the main branch once everything is converted. This eliminates the class of bugs caused by two different languages clashing with each other. Your regular bugs are then harder to debug because you can't be sure that it is or isn't being caused by the fragmentation.

**Comment by PEZ** [comment] 2018-05-12 14:59
Now I have published a version that really should fix the linting problem. The first attempt to fix it was a cherry pick from a branch where the problems was fixed, just that the cherry pick was insufficient. As PR #37 showed, there were more places where the imports didn't work.

Let's close this issue when we have confirmed that I did nail the problem this time.

**Comment by PEZ** [comment] 2018-05-13 11:40
This works now.

**Closed by PEZ** 2018-05-13 11:40 UTC
