### ISSUE TITLE
Ignore form (#_) dimming behaves a bit oddly

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#987] opened 2021-01-25 21:11 UTC
I noticed that dimming will occur in some cases after just `#` and before the `_` is typed. Below you can see `"world"` is dimmed after `#_#` is typed and before the last `_`.

![ignore](https://user-images.githubusercontent.com/12722744/105766558-c25d3000-5f0e-11eb-89d4-516a112c78b2.gif)

**Comment by PEZ** [comment] 2021-01-25 22:15
I think that what might be going on is that `#hello` is parsed as a reader tag, tagging `”world"`. So the first `#_` is dimming out that. Then when you add the `_` it is parsed as two `#_` dimming out `:hello` and `"world"`.

I also think this is consistent with how the Clojure reader would parse it, but I haven't tested that, so could be wrong. In any case, if Calva disagrees with the Clojure reader, it is a bug (even if it is probably hard to fix). If Calva and the Clojure reader agrees, it is not a bug.

We try our best to obey the reader. 😄

**Comment by bpringe** [comment] 2021-01-26 01:06
Oh I see. 

If I evaluate `{#_#:hello "world" :a (+ 5 1)}` I get an error: 

```
; Syntax error reading source at (REPL:81:15).
; Namespaced map must specify a map
```

And also with that form above, clj-kondo complains:

![image](https://user-images.githubusercontent.com/12722744/105785389-9c945300-5f2f-11eb-814b-c782de1453d9.png)

Though I don't really know what's going on with that kondo message...

**Comment by PEZ** [comment] 2021-01-26 06:45
Yeah, I had it a bit confused. The `:` was still there of course. Then the Clojure reader expects it to start a namespaced map. I'm not sure what Calva expects it to be, but either way it is invalid syntax so all bets are off.

Same with the clj-kondo message.  Namespaced maps are notorious and infamous for throwing various Cojure parsers off. And it gets extra tricky when the syntax is broken.

**Comment by PEZ** [comment] 2021-01-27 07:26
Closing this as I doubt it is really fixable in any meaningful way.

**Closed as completed by PEZ** 2021-01-27 07:26 UTC
Labels: highlight
