### ISSUE TITLE
cljfmt isn't found unless project is started

### ISSUE THREAD

**Issue by sirmspencer** [BetterThanTomorrow/calva#2078] opened 2023-02-11 00:47 UTC
`Fetching formatting settings from clojure-lsp failed. Check that you are running a version of clojure-lsp that provides "cljfmt-raw" in serverInfo.`

If I launch vscode I get the above message, and cljfmt wont format correctly.  If I then start my project (lein repl), which happens to include lein-cljfmt, then cljfmt starts formatting correctly.  More interestingly, if I stop the project but don't close vscode, cljfmt continues to format correctly.  

This is a new behavior as of a few days (I was off 2/4 - 2/9)

Im not sure where clojure-lsp is looking for cljfmt, is there somewhere else besides project.clj / plugins I need to be updating?

I think cljfmt had a pretty big changed merged in recently, but can't confirm the timeline.

**Comment by PEZ** [comment] 2023-02-11 07:52
Hello. Thanks for reporting. I'm guessing here, afk and all. 

1. You have Calva's cljfmt config setting set to use clojure-lsp. 
2. clojure-lsp takes a while to start, and it started while you started the project. 

The REPL really shouldn't have anything to do with this. 

Thanks for the heads up about cljfmt changes. Calva uses a pinned version so is not automatically using latest. I'll have a look if we should bump the dependency.

**Comment by sirmspencer** [comment] 2023-03-05 21:17
> You have Calva's cljfmt config setting set to use clojure-lsp.

That is correct.  Makes sense why its happening.  Could be nice to be able to disable that error when pointing to clojure-lsp.

**Comment by bpringe** [comment] 2023-03-05 22:23
> Could be nice to be able to disable that error when pointing to clojure-lsp.

Doesn't this point to an actual issue, though? You want to use cljfmt via clojure-lsp, but the cljfmt config from clojure-lsp isn't found. I might be missing something.

**Comment by sirmspencer** [comment] 2023-03-09 00:25
> Doesn't this point to an actual issue, though? You want to use cljfmt via clojure-lsp, but the cljfmt config from clojure-lsp isn't found. I might be missing something.

I might be missing my OP.  Even more recently, I still occasionally getting the error, but I havn't noticed the formatter not working.  Stand by I'll see if I can get replicable steps (on my end anyway) again.

![image](https://user-images.githubusercontent.com/33734037/223883688-627c649c-84a3-48dd-95e5-99d65c219f2a.png)

**Comment by hkjels** [comment] 2023-04-21 11:58
> > Doesn't this point to an actual issue, though? You want to use cljfmt via clojure-lsp, but the cljfmt config from clojure-lsp isn't found. I might be missing something.
> 
> I might be missing my OP. Even more recently, I still occasionally getting the error, but I havn't noticed the formatter not working. Stand by I'll see if I can get replicable steps (on my end anyway) again.
> 
> ![image](https://user-images.githubusercontent.com/33734037/223883688-627c649c-84a3-48dd-95e5-99d65c219f2a.png)

I'm also getting this on Windows10 although formatting seems to work

**Comment by PEZ** [comment] 2023-04-21 15:21
I think the error means that the formatter will not use the settings provided via clojure-lsp. If you know some form that formats non-standard by those settings, you should be able to confirm this.

We could consider stop showing this as an error, and instead just log it in the dev console.

**Comment by sirmspencer** [comment] 2023-04-21 17:42
> clojure-lsp takes a while to start, and it started while you started the project.

This is the issue.  Formatting eventually starts working.  I don't need to see the error for that few seconds where its still loading.

> We could consider stop showing this as an error, and instead just log it in the dev console.

This and another error I would like to see go to the console and not pop up.  If we can't set it per error message, a general setting to show errors in console would be great.  Should I close this ticket and reopen one in that context?

**Comment by PEZ** [comment] 2023-04-21 19:53
You could open a new ticket for that other message and leave this one open. I think this one should rather be solved than just muted.

**Comment by sirmspencer** [comment] 2023-04-21 19:56
Some more context, the error only shows when lsp is loading.  As soon as the loading icon goes away, I can save without the error.
![image](https://user-images.githubusercontent.com/33734037/233723889-5d962616-52d8-4a05-afcc-642e02c6b99a.png)

**Comment by PEZ** [comment] 2023-04-21 20:21
This VSIX should have a fix for this. I can't reproduce the error easily, though, can you test it, @sirmspencer ?

* https://output.circle-artifacts.com/output/job/c3125eb7-b0b1-4cbb-819a-0fa3383ffe72/artifacts/0/tmp/artifacts/calva-2.0.354-2078-cljfmt-cljlsp-start-bbdb995e.vsix

**Comment by sirmspencer** [comment] 2023-04-21 20:49
Thanks, I'll be able to test it by Monday.

**Comment by sirmspencer** [comment] 2023-04-21 20:55
The larger error goes away, but this shows when trying to save before lsp finishes loading
![image](https://user-images.githubusercontent.com/33734037/233733064-ed36f0d8-9792-412a-b82a-1a6669aa82f0.png)

**Comment by sirmspencer** [comment] 2023-04-24 18:55
I finally rebooted my machine, and the original problem in the OP is back.  The clj error message keeps popping up after clj is done loading.  It goes back to working after starting a repl.

**Comment by bpringe** [comment] 2023-04-27 03:37
> I finally rebooted my machine, and the original problem in the OP is back. The clj error message keeps popping up after clj is done loading. It goes back to working after starting a repl.

@sirmspencer That is with the VSIX @PEZ linked, correct?

**Comment by sirmspencer** [comment] 2023-05-01 22:16
@bpringe No, it creates a constant "cannot read properties of undefined (reading 'isRunning')" error as posted above.

**Comment by PEZ** [comment] 2023-05-02 06:35
> > @sirmspencer That is with the VSIX @PEZ linked, correct?
>
> @bpringe No, it creates a constant "cannot read properties of undefined (reading 'isRunning')" error as posted above.

@sirmspencer It's unclear if you get the error with the new VSIX or with current Calva. Anyway, here's the latest VSIX addressing this problem. Please give it a go and let us know if you still see the problem.

* https://output.circle-artifacts.com/output/job/9f6b4671-9a23-436f-a8ec-32ece2d97dc9/artifacts/0/tmp/artifacts/calva-2.0.354-2078-cljfmt-cljlsp-start-4d3bc494.vsix

**Comment by sirmspencer** [comment] 2023-05-03 00:32
> @sirmspencer It's unclear if you get the error with the new VSIX or with current Calva. Anyway, here's the latest VSIX addressing this problem. Please give it a go and let us know if you still see the problem.

Sorry, I should have quoted the reply even though it was the one below your post.  The error was only for your previous visx.  calva-2.0.354-2078-cljfmt-cljlsp-start-4d3bc494.vsix appears to be working.  I'll double check tomorrow after a system reboot.

**Closed as completed** 2023-05-03 14:28 UTC
Labels: formatting, lsp
