### ISSUE TITLE
Clojure Language Client server crashes when tests files are too large

### ISSUE THREAD

**Issue by billy-mar** [BetterThanTomorrow/calva#1214] opened 2021-06-28 12:18 UTC
Dear Calva Developers,

I use Calva for a couple of weeks and it worked fantastic till last week when I added two very large test files (each approx. 30,000 lines). Tests works (I can execute them with `lein text test/a/b/c_test.clj`) but when I open the project I get:

<img width="1127" alt="1" src="https://user-images.githubusercontent.com/85492429/123634267-219ed380-d812-11eb-8aec-548352fb813a.PNG">
<img width="424" alt="2" src="https://user-images.githubusercontent.com/85492429/123634282-2499c400-d812-11eb-84e2-c56d7a35b5c2.PNG">
<img width="754" alt="3" src="https://user-images.githubusercontent.com/85492429/123634294-26fc1e00-d812-11eb-9af0-db12826c00c6.PNG">

To fix it I just need to rename the files from `.clj` to `.txt` and then open the project again.

I was thinking that Language Server might have some timeout value but I couldn't find it in either in the Calva or Code settings.

Please let me know if you need more info or if I shouldn't not use such large files.

Kind regards,
Billy

**Comment by PEZ** [comment] 2021-06-28 14:26
Thanks for reporting. I'll ping in @ericdallo here since he might have more of a clue what could be going on here. 

The [LSP page on Calva docs](https://calva.io/clojure-lsp/) says that you configure clojure-lsp via it's config file. There's a link there to the settings info. FYI. I don't see anything about a time-ut config there either.

**Comment by ericdallo** [comment] 2021-06-28 15:13
there is no timeout on clojure-lsp, if it crashed, probably some really weird corner case happened and we need the logs to understand what caused.
It's quite rare a issue/bug cause a crash on server, so the logs or a minimal repro project would help understand.

**Comment by bpringe** [comment] 2021-06-29 02:24
@billy-mar Clojure-lsp logs to `/tmp/clojure-lsp.*.out` by default. I think these are the logs Eric is referring to above.

**Comment by billy-mar** [comment] 2021-06-29 10:16
> logs or a minimal repro project would help understand

I created a simple project that reproduces the issue: https://github.com/billy-mar/reproducing_clojure_lsp_or_calva_bug

I'll look into the logs. Thank you @bpringe , @ericdallo and @PEZ .

**Comment by ericdallo** [comment] 2021-06-29 16:28
@billy-mar I tested with emacs / lsp-mode and no crashes happened. It took a while (~30s) to clojure-lsp process the file open as 30.000 lines as text is a lot to send via LSP, but it worked.
The crash happening on Calva is weird, maybe @bpringe can help investigate?

**Comment by billy-mar** [comment] 2021-06-30 08:46
Thank you for testing @ericdallo . Could you please tell me what would be your recommendation for having these files in the project so I can run `lein test` but not processing them by clojure-lsp? `#_:clj-kondo/ignore` ?

**Comment by ericdallo** [comment] 2021-06-30 12:44
I think we don't have that option ATM to ignore a complete file, but I don't think we need that if we understand/fix the crash issue, I still don't understand why it's crashing in your machine but not with me.

**Comment by billy-mar** [comment] 2021-07-05 10:45
I found the problem. I run Calva/LSP inside a container on code-server (like VSCode but for web browser) and I limited amount of memory the container can use. I removed the limitation, open the project again and in some point the LSP was using 6 GiB and the limitation was 4 GiB which means LSP wasn't dying, Linux killed it instead.

Sorry about the bug, please feel free to close it.

Btw. does it make sense to open a feature request for excluding whole files? Maybe on LSP github rather than Calva?

Thank you very much for supporting me.

**Comment by ericdallo** [comment] 2021-07-05 12:34
Not sure it makes sense to exclude the files, that'd be probably a rule on the client than on the server

**Comment by bpringe** [comment] 2021-07-06 04:31
@ericdallo Would the server need to support excluding files in order for the client to tell it what files should be excluded?

**Comment by ericdallo** [comment] 2021-07-06 12:36
@bpringe I don't think the server needs to know anything about that logic, the client can just don't send didOpen/activate the LSP for those files I think

**Comment by bpringe** [comment] 2021-07-07 02:46
Ah, I was thinking the problem didn't require opening the file, but that it crashes just with a file that large in the project. Is that true? If so, we need a way to tell clojure-lsp not to analyze those files during initialization. Is there a way to do that?

**Comment by ericdallo** [comment] 2021-07-07 13:19
I thought it was required with opening the file, could you confirm @billy-mar ?

> Is there a way to do that?

ATM no, we 'd need to know what kind of exception it's happening to know where the problem is, clj-kondo, clojure-lsp. Maybe @billy-mar can get the clojure-lsp log for us?

**Comment by bpringe** [comment] 2021-08-18 02:41
I'm going to close this, but we can reopen it later if it seems like a good idea.

**Closed as completed by bpringe** 2021-08-18 02:41 UTC
Labels: crash, lsp
