### ISSUE TITLE
Add option to format on save

### ISSUE THREAD

**Issue by sirmspencer** [BetterThanTomorrow/calva#817] opened 2020-10-14 18:08 UTC
Im not sure exactly which portions of the code are formatted by which formatters (eg klj-condo vs calva-fmt).  For example I disabled "calva-fmt as Clojure formatter" and everything seems to work the same for me.

Here is my current experience: 
I have "Format as you type" enabled, which correctly puts the cursor at the right indent as I type.  If for example the name of a function changes, no formatting is done as I type.  To fix the formatting, I have two options 1) go to a line that is higher in the tree (the defn line for example) and hit tab, that formats everything that is a child 2) go to the action menu and select "Format Document" to format the whole document

It would be awesome if the formatting of the whole document could occur on save.

**Comment by bpringe** [comment] 2020-10-14 20:00
This is a duplicate of #797. Please add info there if you have more to add. Thanks!

**Closed by bpringe** 2020-10-14 20:00 UTC
