### ISSUE TITLE
Connecting to REPL twice kills all new bash prompts

### ISSUE THREAD

**Issue by tjbrandt** [BetterThanTomorrow/calva#64] opened 2018-08-18 05:42 UTC
This is a pretty odd issue, but I've been able to reproduce it pretty simply in multiple clojure projects, and it took me quite a while to trace it back to this extension. I'd like someone else to try as a sanity check for me, though the repro steps are simple enough that I'm pretty sure it's a Calva problem.

Repro steps:
* Start a repl for a clojure project with `lein repl`
* Open VSCode
* Click the `nREPL` button in the status bar and use the pre-populated host:port
* Wait a few seconds for it to connect
* Click the `nREPL` button in the status bar again to "re-do" the connection to that same host:port
* All subsequent terminals everywhere (in VSCode, in macOS Terminal app, in iTerm2) won't load a bash prompt for me

I noticed this several times yesterday during the work day. If I ever have code changes that require a repl restart, I will often reconnect Calva to that repl in order to get all its functionality. So it's a pretty common workflow for me. Restarting my computer is the only way I've been able to get a bash prompt in any new terminal windows. I tried restarting the terminal, restarting VSCode, killing processes.... nothing seemed to work except a restart.

My System Details:
macOS High Sierra Version 10.13.6
VSCode 1.26.1
Leiningen 2.8.1 on Java 1.8.0_152 Java HotSpot(TM) 64-Bit Server VM
Project dependencies:
    :dependencies [[org.clojure/clojure "1.8.0"]
                   [ring/ring "1.1.6"]]

**Comment by tjbrandt** [comment] 2018-08-19 20:05
Nevermind! I reverted my VSCode version to 1.25 and it works now, so seems to be a VSCode bug with the new release. I'm closing this out.

**Comment by PEZ** [comment] 2018-08-20 07:56
Many thanks for the headsup and the work to isolate the issue. Let's hope the vscode bug gets fixed soon!

**Comment by marcomorain** [comment] 2018-10-15 10:17
This was fixed for me for the last few months, but it started to occur again on Friday.

```
VSCode Version 1.28.1 (1.28.1)
3368db6750222d319c851f6d90eb619d886e08f5
2018-10-11T18:00:44.561Z
```

**Comment by PEZ** [comment] 2018-10-15 11:03
I've got reports in other channels about this. Reopening.

**Comment by eric-hu** [comment] 2018-10-24 11:28
I've run into this recently as well. My coworker and I exchanged notes about it and he can usually recover from this issue by closing VSCode and reopening it. We're both running on macOS, but I'm connecting to a `lein repl` session running in my terminal and he runs it inside Docker.

I've been able to recover without a restart by running `ps aux` and killing it repeatedly until I see a `/usr/bin/java -Dfile.encoding=UTF-8 ...` process. I can then pass that pid to `kill`. `ps` doesn't always show the java process as it also becomes blocking when my computer gets into this state.

**Comment by PEZ** [comment] 2018-10-25 12:37
It is horrible. I have looked at the Calva code and can't see that I do anything strange. Just using the VS Code API. We must probably dig around the issues on VS Code itself.

**Comment by PEZ** [comment] 2018-10-25 12:39
Also, I wonder why I do not experience this. On any of my two computers.

**Comment by slipset** [comment] 2018-10-26 05:43
We had a clojure workshop yesterday, and observed the terminal-freeze as well.

**Comment by eric-hu** [comment] 2018-10-26 09:55
Is there anything I could run to generate helpful diagnostic info for you the next time I come across this?

**Comment by tjbrandt** [comment] 2018-10-26 12:55
I still think it’s a VSCode issue, because I’ve kept my VS

**Comment by tjbrandt** [comment] 2018-10-26 12:58
Sorry wrong button. I still think it’s VSCode because I experienced the problem originally after upgrading from 1.25 to 1.26, so I effectively pinned my VSCode version to 1.25 and it went away. Same thing happened with one of the more recent VSCode releases: I decided to try to upgrade to see if it was fixed, and the problem was still there, so I reverted to 1.25 again. I haven’t had to change my Calva extension version one way or another.

**Comment by Ken-2scientists** [comment] 2018-11-26 02:43
I noticed that I could resolve my issue by updating the default shell that the VS Code terminal launches. My user profile on macOS is set to use `zsh`, but VS Code defaults to `bash`. I updated the user setting:
```
{
    "terminal.integrated.shell.osx": "/bin/zsh"
}
```
That addressed the issue I reported immediately above [above](https://github.com/BetterThanTomorrow/calva/issues/64#issuecomment-441500332), but it doesn't resolve the issue that the OP identified. I can easily reproduce the OP's issue by clicking the `nREPL` button in the status bar once already connected (i.e. re-connecting). This causes all terminals to hang until VS Code is restarted.

**Comment by PEZ** [comment] 2018-11-26 21:40
@Ken-2scientists , oh, wow, thanks for this help with reproducing and investigating! I'll try it out myself and see if I can make it happen on my machine as well.

**Comment by adairdavid** [comment] 2018-12-07 17:58
I have run into this issue as well. I noticed that after killing all "standard" processes for my development stack, there was still a `java` process that I could not account for. After killing that remaining `java` process, all terminals were able to proceed with loading the shell.

**Comment by PEZ** [comment] 2018-12-25 11:19
As I can't reproduce this I need help checking if I might have fixed it with the latest Calva, `v1.3.60`. It has a completely rewritten socket management for the nREPL connection. Previously sockets were opened and closed for each nREPL message sent and received, while now there is a socket connection opened when Calva connects and that connection is then used for all messages. @marcomorain flagged this as a suspect source of this bug, and this is in the hope that that suspicion found the right suspect.

**Comment by tjbrandt** [comment] 2018-12-27 17:15
Thanks for your work on this, PEZ, but I'm still able to reproduce the problem on my Mac even after updating to VSCode 1.30.1 and Calva 1.3.60. Sorry it's been such a headache to try to fix :( If your rewritten code doesn't fix it seems like it's probably pointing to a VSCode bug not a Calva bug.

Here were my repro steps this time, and I went though it three times with the same result:
1. Open a Clojure project
2. Open the VSCode integrated terminal
3. Start the REPL for your project
4. Connect Calva to the REPL using the `Calva: Connect` command (or the nREPL status bar button)
5. See if you can open a new bash instance anywhere (using iTerm in my case): it should work this time
6. Now, shut down your REPL at the VSCode integrated terminal prompt using `quit`
7. Start the REPL up again at the same integrated terminal prompt
8. Connect Calva to the REPL using the `Calva: Connect` command (or the nREPL status bar button)
9. This time, if you try to open a new bash terminal anywhere, the terminal just hangs (my cursor just sits and blinks)
10. Shut down the REPL at the integrated terminal using `quit` then shut down that integrated terminal instance using `exit`
11. Shut down the connected Calva REPL instance in the integrated terminal as well using `quit` then `exit`
12. Quit VSCode
13. The terminal that was hanging in step number 9 now suddenly finishes opening and gives you a bash prompt

**Comment by PEZ** [comment] 2018-12-27 22:49
Thanks for the detailed repro! I'm not at a computer so I can try it out,
but will be doing that first thing when I'm back.

**Comment by PEZ** [comment] 2018-12-28 22:11
I still can't reproduce this. Very strange!

**Comment by tjbrandt** [comment] 2018-12-28 22:14
It looks like everyone who has had a problem is on a Mac, so it might be Mac-specific.

**Comment by PEZ** [comment] 2018-12-28 22:16
Most sane people are on Mac. Not saying I am sane, but I do use Mac.

**Comment by tjbrandt** [comment] 2018-12-28 22:17
Ok, yeah that's pretty weird you can't repro then. Hmmmmm.

**Comment by abtiddle** [comment] 2019-02-28 21:48
Description:

Terminal messages do not display

Environment:

• macOS High Sierra, Version 10.13.3
• Visual Studio Code, Version 1.31.1 (1.31.1)
• java version "11.0.2" 2019-01-15 LTS
  Java(TM) SE Runtime Environment 18.9 (build 11.0.2+9-LTS)
  Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.2+9-LTS, mixed mode)

Steps:

1. Run Terminal
2. lein new app my-app
3. cd my-app
4. lein repl
5. Run Visual Studio Code
   File > Open > my-app > button Open
6. Select a file, i.e. src/my_app/core.clj
7. Click icon nREPL > <Enter>
8. Select window Terminal > Shell > New Window
9. Expect: Startup messages to display
10. Actual: No startup messages display

Note 1:

11. Select window Visual Studio Code
12. File > Close Folder
13. Terminal window displays startup messages and can not be used. 

Note 2:

Do step 7 twice and all new Terminal windows are no longer usable; even if you exit Terminal and re-start. To fix, have to force delete each running java processes; used Activity Monitor.

**Comment by PEZ** [comment] 2019-03-01 07:14
Thanks for the detailed repro!

This whole terminal business might be over soon, because we are replacing the terminal REPLs with a a REPL window of our own, written totally from scratch (by @mseddon) as a WebView. It is not quite ready for release yet, but I do use it myself for all my Clojure work.

Uploading it here so that you can try it out and, if you can stand the warts, maybe use it instead of the currently released Calva, as I do.

[clojure4vscode-1.3.64-SNAPSHOT.zip](https://github.com/BetterThanTomorrow/calva/files/2918283/clojure4vscode-1.3.64-SNAPSHOT.zip)

(You'll need to rename the `.zip` extension to `.vsix`.)

Feedback welcome! Preferably in the #calva-dev channel of the Clojurians Slack.

**Comment by PEZ** [comment] 2019-08-05 10:48
Closing this since it is probably not relevant for new Calva.

**Closed by PEZ** 2019-08-05 10:48 UTC
