### ISSUE TITLE
Backspace should not delete both form and space in one run

### ISSUE THREAD

**Issue by clyfe** [BetterThanTomorrow/calva#985] opened 2021-01-24 20:07 UTC
`"   (|)"` + `backspace` yields `""`; should yield `"   "` (& 2nd backspace to delete the space).
So, backspace should delete the form and the space separately.

**Comment by PEZ** [comment] 2021-01-26 17:25
I can't reproduce this.

**Comment by PEZ** [comment] 2021-01-26 17:33
When I try this it works as I have designed it to work. Inside strings (which looks to be the issue reported) it leaves the space. Outside strings if empty parens are the last thing in a form, we clean the space away. If it not the last thing in a form it leaves spaces alone.

**Comment by PEZ** [comment] 2021-01-26 18:51
Closing this as the behaviour is by design. We might be introducing some settings later for controlling how aggressive the formatting is, and if so we should remember that this might be a knob someone wants to tweak.

Many thanks for the issue and for the PR. I was a bit too quick in assessing the report, which caused us all this confusion.

**Closed as completed by PEZ** 2021-01-26 18:51 UTC
Labels: formatting

**Comment by clyfe** [comment] 2021-01-28 09:11
I'd like to bring one more argument here. Scenario:

```clojure
(defn f []
  (|))
```

I have a form in the clipboard; I want to place it instead the parens there.
Press `backspace` cursor jumps on the first line. Have to `enter` before paste.

The bottom line is: there's an intermediary position of interest & often-use that the current behavior completly eschews.
The position of interest is:

```clojure
(defn f []
  |)
```
