### ISSUE TITLE
VSCode crashes on "Load current namespace in REPL terminal"

### ISSUE THREAD

**Issue by alzadude** [BetterThanTomorrow/calva#175] opened 2019-05-01 14:46 UTC
Hi there,

I'm not sure what changed recently (!) but when I execute "Load current namespace in REPL terminal" after starting an nrepl server and connecting successfully, VSCode crashes with the attached error message (see below)!

This is the first time I've used Calva/VSCode for a month or so, so I guess it could be a VSCode or Windows change? Is anyone else seeing this issue?

Calva: 1.3.66, Use WSL: true
Clojure: 1.10.0.411
Connect REPLCommand: `clj -Sdeps '{:deps {reply {:mvn/version "0.4.3"}}}' -m reply.main --color --attach`

VSCode -> Help -> About

Version: 1.33.1 (system setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Any ideas?

![Untitled](https://user-images.githubusercontent.com/1161048/57021196-768b3300-6c23-11e9-92f4-772540d38e5c.png)

deps.edn
```
{:paths ["src"]
 :deps
 {org.clojure/clojure {:mvn/version "1.10.0"}
  org.clojure/clojurescript {:mvn/version "1.10.329"}
  org.clojure/core.async {:mvn/version "0.4.490"}}
 :aliases {:dev {:extra-paths ["test"]
                 :extra-deps {org.clojure/test.check {:mvn/version "0.9.0"}
                              plumula/mimolette {:mvn/version "0.2.1"}}}
           :test {:extra-deps {com.cognitect/test-runner {:git/url "https://github.com/cognitect-labs/test-runner.git"
                                                          :sha "cb96e80f6f3d3b307c59cbeb49bb0dcb3a2a780b"}}
                  :main-opts ["-m" "cognitect.test-runner"]}
           :test-cljs {:extra-deps {olical/cljs-test-runner {:mvn/version "3.5.0"}}
                       :main-opts ["-m" "cljs-test-runner.main"]}
           :nrepl-server {:extra-deps {cider/cider-nrepl {:mvn/version "0.21.1"}
                                       cider/piggieback {:mvn/version "0.4.0"}
                                       org.clojure/tools.namespace {:mvn/version "0.2.11"}}
                          :main-opts ["-m" "nrepl.cmdline"
                                      "--middleware" "[cider.nrepl/cider-middleware,cider.piggieback/wrap-cljs-repl]"]}
           :outdated {:extra-deps {olical/depot {:mvn/version "1.7.0"}}
                      :main-opts ["-m" "depot.outdated.main"]}}}
```

**Comment by PEZ** [comment] 2019-05-01 15:17
Looks like it is the terminal that crashes. There are some settings for using a new renderer in the terminal (I don't remember the phrasing. Long shot, but try to fiddle with that setting and see if it helps.

**Comment by alzadude** [comment] 2019-05-01 22:01
> Looks like it is the terminal that crashes. There are some settings for using a new renderer in the terminal (I don't remember the phrasing. Long shot, but try to fiddle with that setting and see if it helps.

Ah thanks, indeed after creating the issue, I found this issue for VSCode (which has the same error message, but a different way to reproduce (which I didn't try yet):

https://github.com/Microsoft/vscode/issues/68513

One comment on that issue suggested setting `"terminal.integrated.windowsEnableConpty": false`, however that didn't resolve the issue for me, even after a VSCode restart (it still crashes).

Any other suggestions welcome.

I can't quite believe VSCode gets stable releases with these kinds of issues (full crashes), it seems to me that they're not doing enough testing!

**Comment by PEZ** [comment] 2019-05-02 07:53
You could try using an earlier version of VS Code.

If you're brave enough to run something much less tested than VS Code's latest release, you're welcome to pick up the latest dev build of Calva 2 that I posted in #calva-dev on Clojurians Slack the other day. :smile: It does not rely on terminals for the repl. Of course, lots of new rough edges, but anyway.

**Comment by alzadude** [comment] 2019-05-07 12:58
> You could try using an earlier version of VS Code.
> If you're brave enough to run something much less tested than VS Code's latest release, you're welcome to pick up the latest dev build of Calva 2 that I posted in #calva-dev on Clojurians Slack the other day. 😄 It does not rely on terminals for the repl. Of course, lots of new rough edges, but anyway.

Hi @PEZ!

For my daily driver I'd like to stay on the stable versions of VSCode and Calva if possible.. Would you recommend me to create a VSCode issue for this, or would you be willing to do a bit of triage just to check it's not anything on the Calva side? If I create a VSCode issue, I'm wondering if they'll just ping it straight back over..

**Comment by PEZ** [comment] 2019-05-07 16:12
This is hard for me to test. I don't have a Windows testing environment set up. 

This could be a Calva issue. The terminals have been problematic before. My solution is to throw them out and create the repl windows in another way. But it is at least a few weeks before that is ready for release.

**Comment by alzadude** [comment] 2019-05-25 19:42
> This is hard for me to test. I don't have a Windows testing environment set up.
> This could be a Calva issue. The terminals have been problematic before. My solution is to throw them out and create the repl windows in another way. But it is at least a few weeks before that is ready for release.

Ah this makes me sad 🙁 I didn't realise that releases weren't getting tested on Windows.. 

Does this imply there isn't really a stable Calva version for Windows right now? Just trying to think of a solution for using Calva as a daily driver.. It was working pretty well for me until this issue cropped up.

Of course I can work around it by select all + evaluate selection, but sometimes I forget..

Btw, I've upgraded to VSCode 1.34, but I still get the same crash. From what I read, VSCode will still use Winpty instead of ConPTY in my case, because I'm still on Windows 10 1809 (10.0.17763)

**Comment by PEZ** [comment] 2019-06-05 16:23
Now the new version of Calva is out. It is published as a new extension. Please check if it resolves this issue for you.

**Comment by alzadude** [comment] 2019-06-20 18:06
> Now the new version of Calva is out. It is published as a new extension. Please check if it resolves this issue for you.

Hi @PEZ ah great news!

I just downloaded and it looks like I'm not yet able to check if it resolves the issue, due to other changes in this new version... I am working with a ClojureScript project targeting NodeJS, and I was previously starting a deps.edn based nrepl server, and then using `calva.startCLJSREPLCommand` with value `(require 'cljs.repl.node) (cider.piggieback/cljs-repl (cljs.repl.node/repl-env))` to launch a Piggieback repl backed by NodeJS.. It seems I can no longer do this with the new version?

What are my options for working with NodeJS projects, should I try to setup Figwheel Main to use NodeJS? I'm not targeting the browser..

Thanks!

**Comment by PEZ** [comment] 2019-06-21 08:07
Oh, I'll have a look at this. I think I must rework some of the CLJS support. When it got more helpful with the most common tools, it also closed the door to custom setups...

I will fix that. Putting it on high priority, but can't give an ETA.

Personally, I reach for `shadow-cljs` when targeting NodeJS. Haven't tried Figwheel Main, outside web projects, so don't know how that compares.

**Comment by alzadude** [comment] 2019-06-21 14:35
> Personally, I reach for shadow-cljs when targeting NodeJS. Haven't tried Figwheel Main, outside web projects, so don't know how that compares.

I managed to make some progress with Figwheel Main on Node, but ultimately haven't yet got it working yet.. 

I defined a `dev.cljs.edn` like this:
```
{:main my.app
 :target :nodejs}
```
Then I connect to a running repl server, select Figwheel Main from the drop-down, select the `dev` build from the drop-down, and the CLJS repl appears, in a `cljs.user` namespace as I would expect, so that's promising. Btw I reset `calva.startCLJSREPLCommand` to the default value.

However, when I send forms from a cljs file to the CLJS repl for evaluation, the CLJS repl seems to be switching to the `user` namespace to evaluate them, and then switches back to the `cljs.user` namespace? As such, subsequent evaluations don't work if they depend on previous evaluations, since these were defined in a different namespace. Do you know what is going on here? I'm not sure what to do next, other than try with Shadow CLJS, but I've never used that before.

Note: I'm starting an nrepl server manually and then connecting to it (rather than using the new jack-in feature), because I tried that and it seems to assume I have Clojure installed on Windows (it complains about a missing `clojure.ps1` file), but I am using WSL and have Clojure and Java installed there, I don't wish to install these on Windows.

For reference my `deps.edn` is listed below:

```
{:paths ["src"]
 :deps
 {org.clojure/clojure {:mvn/version "1.10.1"}
  org.clojure/clojurescript {:mvn/version "1.10.520"}}
 :aliases {:test-cljs {:extra-deps {olical/cljs-test-runner {:mvn/version "3.7.0"}}
                       :main-opts ["-m" "cljs-test-runner.main"]}
           :compile-cljs {:main-opts ["-m" "cljs.main" "-co" "compile-opts.edn" "-c" "shazam.cli"]}
           :nrepl-server {:extra-deps {cider/cider-nrepl {:mvn/version "0.21.1"}
                                       cider/piggieback {:mvn/version "0.4.1"}
                                       com.bhauman/figwheel-main {:mvn/version "0.2.1"}
                                       com.bhauman/rebel-readline-cljs {:mvn/version "0.1.4"}
                                       org.clojure/tools.namespace {:mvn/version "0.3.0"}}
                          :main-opts ["-m" "nrepl.cmdline"
                                      "--middleware" "[cider.nrepl/cider-middleware,cider.piggieback/wrap-cljs-repl]"]}}}
```

**Comment by PEZ** [comment] 2019-06-22 07:36
I don't have Windows, but there is some WSL support in Calva. Have you read this? https://github.com/BetterThanTomorrow/calva/wiki/Using-with-WSL  (Not sure it'll help for your jack-in, but asking anyway.)

**Comment by PEZ** [comment] 2019-06-22 12:11
Maybe this could be relevant as well: https://github.com/BetterThanTomorrow/calva/wiki/VS-Code-Remote-Development

**Comment by alzadude** [comment] 2019-06-22 13:21
> I don't have Windows, but there is some WSL support in Calva. Have you read this? https://github.com/BetterThanTomorrow/calva/wiki/Using-with-WSL  (Not sure it'll help for your jack-in, but asking anyway.)

Hi @PEZ yes I've read through that one, and have followed the steps.

> Maybe this could be relevant as well: https://github.com/BetterThanTomorrow/calva/wiki/VS-Code-Remote-Development

Interesting, although I don't mind running VSCode/Calva on the Windows side, since it's GUI stuff. It's just the CLI stuff and dev tools that I prefer to keep in WSL, since they're easier to install with all the dependencies etc.

In any case, I'm slightly concerned about the behaviour I'm seeing in the new version, which I mentioned in my earlier comment:

> However, when I send forms from a cljs file to the CLJS repl for evaluation, the CLJS repl seems to be switching to the user namespace to evaluate them, and then switches back to the cljs.user namespace? As such, subsequent evaluations don't work if they depend on previous evaluations, since these were defined in a different namespace.

This must be a bug right? Is anyone else seeing this, or is it Windows/WSL specific? Just wondering whether to create a separate issue for this. With this basic evaluation not working for me, I can't really use the new version for ClojureScript projects. n.b. I get this issue regardless of Figwheel Main+browser or Figwheel Main+NodeJS. I suppose I could try without WSL (i.e. install Java/Clojure/Node on Windows) since that's the officially sanctioned approach, just to see if this issue still ocurrs?

I was also worried about the popup I see with the new version that states the old version will be removed from the VSCode marketplace soon? I'd rather it wasn't removed any time soon if possible please, until these issues are resolved!

**Comment by PEZ** [comment] 2019-06-22 15:56
> However, when I send forms from a cljs file to the CLJS repl for evaluation, the CLJS repl seems to be switching to the user namespace to evaluate them, and then switches back to the cljs.user namespace? As such, subsequent evaluations don't work if they depend on previous evaluations, since these were defined in a different namespace.
> > This must be a bug right? Is anyone else seeing this, or is it Windows/WSL specific?

It depends on what the namespace of the file is. If it is`user` it rather sounds like things are working as designed. The REPL window temporarily switches to the namespace of the file to evaluate the form, then back to whatever namespace the repl window had before. If you want to switch namespace of the repl window to that of the file, use `ctrl+alt+c ctrl+alt+n`.

**Comment by PEZ** [comment] 2019-06-22 15:59
> I'd rather it wasn't removed any time soon if possible please, until these issues are resolved!

Yes, don't worry. Calva Legacy will stay until we've sorted out the issues. But when that's sorted, boom!

**Comment by PEZ** [comment] 2019-08-01 10:11
It is getting time to remove Calva Legacy from the Marketplace, as it is causing confusion. If someone still find issues with things that work in Legacy, but not in the new version, please speak up now and I'll address those issues if I deem them serious enough before removing the Legacy version.

**Comment by alzadude** [comment] 2019-08-01 21:33
Hi @PEZ 

I've fully switched to the new version now (still some separate problems that I've created new GH issues for as you know), but just commenting to confirm I'm not using the old version any more, the new version is sufficient for me as a daily driver now.

Thanks 🙂

**Comment by PEZ** [comment] 2019-08-02 13:53
Thanks for quick reply!

Can I close this issue now? With the title it has it might scare people from using Calva, and since that title isn't relevant for the current version...

**Closed** 2019-08-05 10:56 UTC

**Comment by alzadude** [comment] 2019-08-05 11:36
> Thanks for quick reply!
> Can I close this issue now? With the title it has it might scare people from using Calva, and since that title isn't relevant for the current version...

Hi @PEZ, apologies for not replying sooner but yes this issue can be closed (and I can see you have done that already) 🙂
