### ISSUE TITLE
Jack in shadow-cljs, command in output ends up as "npx <"

### ISSUE THREAD

**Issue by Tebro** [BetterThanTomorrow/calva#283] opened 2019-08-15 10:02 UTC
When running jack in and selecting shadow-cljs it ends up running "npx <".

Running on Linux.

Task output:

```
> Executing task: npx <


ERROR: You must supply a command.

Execute binaries from npm packages.

  npx [options] <command>[@version] [command-arg]...

  npx [options] [-p|--package <package>]... <command> [command-arg]...

  npx [options] -c '<command-string>'

  npx --shell-auto-fallback [shell]
.....
```

**Comment by PEZ** [comment] 2019-08-15 17:50
Thanks! What shell do you use as default in VS Code?

**Comment by Tebro** [comment] 2019-08-16 06:35
My default shell is fish

**Comment by PEZ** [comment] 2019-08-16 10:20
Thanks for making that test. It was the next thing I was going to ask you to do of course. :smile: Now I am out of ideas. But also, I am looking a bit more closely on the output you have provided. It doesn't look like a quoting issue at all (which I initially thought it might be).

Some more questions then:
1. Which version of Calva are you using?
2. Do you get the popup asking which builds to start, before the task is started?

**Comment by Tebro** [comment] 2019-08-16 13:16
The version is 2.0.31

I do get the popup asking which build to use

**Comment by sebn** [comment] 2019-08-30 09:21
@Tebro By any chance, do you have some dependency name as string? e.g.:

```clojure
{:source-paths
 ["..."]

 :dependencies
 [["whatever.awesome/dependency" "x.x.x"]] ; <- Here, double-quotes around the name

 :builds
 {}}
```

In which case, does turning it into a symbol fix the issue? e.g.:

```clojure
{:source-paths
 ["..."]

 :dependencies
 [[whatever.awesome/dependency "x.x.x"]] ; <- Same without the double-quotes for name

 :builds
 {}}

```

**Comment by sebn** [comment] 2019-08-30 17:07
I believe I switched between mouse and keyboard without thinking about it to select the build(s) while trying to reproduce the issue...

What seems to work every time:

- Run the *Calva: Start a project REPL and connect (aka Jack-In)* command
- Check at least 1 build using the mouse and click on *OK*

What seems to fail every time:

- Run the *Calva: Start a project REPL and connect (aka Jack-In)* command
- Make sure no build is selected and the *Select builds to start* is focused
- Move to the first build using down arrow on keyboard and press Enter

Mouse-selected build(s) are automatically selected on next run, I believe this is was the error was *magically* disappearing, even when using the keyboard.

I'll try to reproduce in debug mode this evening to make sure it actually produces the broken build data that makes the `npx` command fail.

**Comment by PEZ** [comment] 2019-08-30 19:03
Thanks! I can reproduce this on my Mac now. Or something similar to it:

* If I select build using the mouse, the build's selection status gets toggled, and the menu stays open.
* If I press <kbd>enter</kbd> when a build is highlighted, nothing happens with the build's selection, and the menu is submitted.

So, at least on Mac, the UI seems to be designed such that <kbd>enter</kbd> submits the menu and mouse click on a menu item toggles it. <kbd>space</kbd> is used for toggling the selection using the keyboard.

The real bug here is that Calva does not validate the selection.

**Comment by sebn** [comment] 2019-08-30 20:11
When opening the command palette with <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>, typing a few chars + some arrow keys to retrieve the *Jack-in* command, then validating with <kbd>enter</kbd>, the build selection box shows at the same place and also looks like some kind of drop-down menu, so couldn't one easily assume builds can be selected the same way as commands?

Also, when typing <kbd>esc</kbd> from the build selection box, the `npx` command is run (ending up with the same error).

Would making those small UX improvements be valuable?

**Comment by PEZ** [comment] 2019-08-31 09:54
The menu is a built in vscode widget, and I don't think it allows for altering that behaviour. The difference between the builds menu and the Jack-in project type menu is that the builds menu allows multiple selections. So there is an OK button there which is bound to the <kbd>enter</kbd> key.

Here's the API for the QuickPick widget: https://code.visualstudio.com/api/references/vscode-api#QuickPick<T>

I have added some validation for this in the branch were we are reworking much of the jack-in code. It now aborts the jack-in when there is no build selected, including when <kbd>esc</kbd> is pressed. That's better, but there will still be a problem for when the user wants to select more than one build and presses <kbd>enter</kbd> on the last one, thinking that selects it, a situation I can't detect. But maybe, by then the user has learnt how the UI works.

**Comment by Tebro** [comment] 2019-09-03 07:14
Reading through this it makes sense, I no longer use VSCode for Clojure (for other reasons), but good to know this helps others.

**Comment by PEZ** [comment] 2019-09-03 07:26
What are you using instead, if I may ask?

**Comment by Tebro** [comment] 2019-09-03 08:55
VIM.

**Comment by PEZ** [comment] 2019-09-04 07:12
Thanks for clarifying it a bit. I didn't know Calva and the VIM Plugin were incompatible. Is it something else than what is covered [here](https://github.com/BetterThanTomorrow/calva/wiki/Using-with-VIM-extension)?

**Comment by PEZ** [comment] 2019-09-04 07:14
(As an old `vi` user, I often have found the `vi` modes in other editors quite underwhelming, `evil` mode in Emacs being an exception.)

**Comment by Tebro** [comment] 2019-09-04 07:27
In my opinion the paredit part is fundamentally incompatible with (at least my style of) vim editing. I tried to go without the vi mode, but it seems I can no longer function without it.

I agree with your comment about evil being the only vi mode that works well.

**Comment by PEZ** [comment] 2019-09-04 07:34
If you have some time, I'd like to chat some about this. Not sure I can do very much about it, but at least I'd be more informed about the problem. You'll find me as `@pez` on Clojurian's Slack.

**Comment by PEZ** [comment] 2019-09-26 14:03
Closing this, as there is not very much we can do about it at the Calva end of things.

**Closed by PEZ** 2019-09-26 14:03 UTC
Labels: help wanted, jack-in
