### ISSUE TITLE
Simple node repl for Clojurescript, without Figwheel or Shadow-cljs

### ISSUE THREAD

**Issue by alzadude** [BetterThanTomorrow/calva#66] opened 2018-08-23 00:22 UTC
Hi there,

I am working on some Clojurescript projects that are just simple command line apps, targeting Node js.. as such, I don't need the all the features of Figwheel or Shadow-cljs e.g. reloading and browser support.

I did manage to get the repl working for Figwheel and Shadow-cljs, but it was a bit cumbersome since I needed to create and compile a 'main' cljs script first, and then manually run the resulting js script with Node before the Figwheel or Shadow-cljs would connect (in addition running to the nrepl server with `lein repl`). Even then I had (Figwheel) issues, such as not being able to evaluate code with `ctrl-alt-v e` in a different namespace, until said namespace had been loaded by Figwheel.. but the only way I could get that to work was by changing the file in the other namespace and saving it. This all seemed a bit complex for what I needed, so I wondered if there was a simpler solution.

I wondered if it would be possible to avoid the manual invocation of Node, and also be able to start coding from scratch without needing to create a 'main' cljs script first, by using the Node repl in Clojure 1.9. Then I found the following article describing a process that worked for Cider/Emacs, and I thought I'd try it with Calva:

[https://oli.me.uk/2018-03-04-clojure-and-clojurescript-nrepl-with-clojure-cli/](https://oli.me.uk/2018-03-04-clojure-and-clojurescript-nrepl-with-clojure-cli/)

The result is that it 'nearly' worked.. after starting an nrepl server with `lein repl` and the needed `project.clj` config (see below), I could start a Clojurescript repl (backed by Node) from the Clojure repl in Calva by running

```
(cider.piggieback/cljs-repl (cljs.repl.node/repl-env))
```

I then updated the Calva `calva.startCLJSREPLCommand` setting to use this command for starting a Clojurescript repl. The result was promising, and Calva seemed to think the cljs repl was running!

However, when I tried to evaluate cljs code with `ctrl-alt-v e` I got various errors, for example when evaluating `(ns my-app.main)` I get

```
Evaluating:
my-app.main
Error: repl:13
throw e__9740__auto___19169;
^

ReferenceError: my_app is not defined
    at repl:1:59
    at repl:9:3
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Domain.<anonymous> ([stdin]:56:38)
    at Domain.run (domain.js:242:14)
    at Socket.<anonymous> ([stdin]:55:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
```

And when evaluating `(def my-vals ["a" "b" "c"])` I get

```
Evaluating:
my-vals
Error: WARNING: Use of undeclared Var /my-vals at line 1 <cljs repl>

repl:1
try{cljs.core.pr_str((function (){var ret__9739__auto__ = .my_vals;
                                                          ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Domain.<anonymous> ([stdin]:56:38)
    at Domain.run (domain.js:242:14)
    at Socket.<anonymous> ([stdin]:55:29)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
```

Am I wrong in expecting this solution to work for Cider/Calva? I was kind of hopeful since it's working for Cider/Emacs...

Thanks!

My `project.clj` config:

```
(defproject my-app "0.1.0-SNAPSHOT"
  :description "my-app"
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [org.clojure/clojurescript "1.10.64"]]
  :profiles {
             :repl {:plugins [[cider/cider-nrepl "0.18.0"]]
                    :dependencies [[org.clojure/tools.nrepl "0.2.13"]
                                   [cider/piggieback "0.3.8"]]
                    :repl-options {:nrepl-middleware [cider.piggieback/wrap-cljs-repl]}}})
```

**Comment by PEZ** [comment] 2018-08-23 07:06
Hello! That does look promising. And the errors are very strange. I have not tried this myself and haven't actively tried to make it work, so am not sure what we can expect.

I really would like Calva to work for this and will try to take part in the investigation (even though right now a bit too much going on at work so limited bandwidth).

What happens if you evaluate the file (default binding `ctrl+alt+v ENTER`)?

**Comment by alzadude** [comment] 2018-08-23 11:35
Hi there,

Ok I tried to evaluate the file (`ctrl+alt+v ENTER`) and I just got

```
Evaluating file: main.cljs
No results from file evaluation.
```

Btw, my Clojure code above to start the Clojurescript repl is not correct, since the `cljs.repl.node` namespace is not yet loaded. The correct code is

```
(require 'cljs.repl.node) (cider.piggieback/cljs-repl (cljs.repl.node/repl-env))
```

(I didn't need to `require` for `cider.piggieback`, I can only assume this is already loaded at some point when the lein repl starts..?)

**Comment by alzadude** [comment] 2018-10-25 12:50
Hi @PEZ 

Just to follow this up.. I finally managed to get this "simple Node repl" scenario working with Calva, but I'm not sure what I did differently or changed compared to my earlier comments to make it work.

In any case, if you're interested this is a working `project.clj`:
```
(defproject calva-simple-node-repl "0.1.0-SNAPSHOT"
  :description ""
  :dependencies [[org.clojure/clojure "1.9.0"]
                 [org.clojure/clojurescript "1.10.339"]
                 [org.clojure/data.xml "0.2.0-SNAPSHOT"]]
  :profiles {:repl {:plugins [[cider/cider-nrepl "0.18.0"]]
                    :dependencies [[cider/piggieback "0.3.9"]
                                   [org.clojure/tools.nrepl "0.2.13"]]
                    :source-paths ["src"]
                    :repl-options {:nrepl-middleware [cider.piggieback/wrap-cljs-repl]}}})
```

And I set `calva.startCLJSREPLCommand` to:
```
(require 'cljs.repl.node) (cider.piggieback/cljs-repl (cljs.repl.node/repl-env))
```
With this setup, evaluation of forms & selections works, either direct `ctrl+alt+v e` or in the REPL `ctrl+alt+v alt+e`.

However, load current namespace in REPL `ctrl+alt+v alt+e` and evaluate file `ctrl+alt+v enter` don't seem to work? Although I noticed Calva prints something when activated that may be related: 

"The evaluate file command does not seem to work in shadow-cljs clojurescript repls. A workaround, that sometimes suffices, is to select all contents of the file and evaluate it."

Seems this also affects this simple Node repl scenario, where I am currently using the same workaround. 

It would be great if evaluate file could be made to work!

Also, I was wondering if this setup would be useful in the docs for people who want to use the same simple Node repl scenario without Figwheel or Shadow etc. I also have the same setup working without Leiningen, where I use deps.clj to start an nrepl server, and `calva.startCLJSREPLCommand` starts a repl-y nrepl client. I could provide docs for that setup also.

Thanks,

Alex.

**Comment by PEZ** [comment] 2018-10-26 06:44
Yes, it is long overdue to look at why evaluating the file does not work in node environments. I agree it seems likely that both this setup and the shadow-cljs scenario probably are affected by the same root cause.

Yes, this setup would be great to have in the docs. It is super duper stuff! I don't know if you can edit the wiki? If so then please make a page for it and then we (as in you and I) can find a good place in the README to link to it.

**Comment by alzadude** [comment] 2018-12-10 12:48
Hi @PEZ 

No I can't edit the wiki it seems.. Shall I just document the steps in this issue, and then you can copy and paste into a wiki page (or the README)?

The steps in this case will be for the following two separate procedures:

1. Using clj instead of lein
- Example deps.edn file
- Use clj to start an nrepl server
- Edit calva.connectREPLCommand to use clj to start a repl-y nrepl client, passing the hostname and port

2. Using a simple node repl for cljs, instead of Figwheel or Shadow-cljs
- Example deps.edn file
- Edit calva.startCLJSREPLCommand

Let me know 🙂

**Comment by PEZ** [comment] 2019-08-05 11:07
Hello again,

A while ago I added a new setting to Calva, `calva.customCljsRepl`, that possibly fixes this for you:

```json
"calva.customCljsRepl": {
        "name": "My Custom CLJS REPL",
        "startCode": "",
        "connectedRegExp": "To quit, type: :cljs/quit",
        "printThisLineRegExp": "",
        "tellUserToStartRegExp": ""
    },
```

I have yet to document it, but you can look at JUXT Edge for a usage example: https://github.com/juxt/edge/blob/master/lib/edge-app-template/links/cljs_calva_settings.json

**Comment by bpringe** [comment] 2020-05-12 21:53
Seeing as how this issue is a bit stale and the `calva.customCljsRepl` setting may provide a solution, can we close this?

**Comment by bpringe** [comment] 2020-11-25 18:03
https://calva.io/connect-sequences/ I believe functionality and documentation around this has been improved over time. Closing this now. Please reopen if needed.

**Comment by bpringe** [comment] 2020-11-25 18:12
Actually, changed my mind on closing :smile:. Maybe we could use some documentation around this with the new custom connect sequences? @alzadude What are your thoughts? It's just not something I've tried / needed myself.

**Comment by PEZ** [comment] 2021-04-10 20:09
Pasting the sequence setting that possibly is what would solve the issue. Well spotted, @xavi!

```json
    "calva.replConnectSequences": [
        {
            "projectType": "deps.edn",
            "name": "plain cljs node repl",
            "cljsType": {
                "dependsOn": "User provided",
                "connectCode": "(do (require 'cljs.repl.node) (cider.piggieback/cljs-repl (cljs.repl.node/repl-env)))"
            }
        }
    ]
```

**Closed** 2021-04-10 20:11 UTC
