### ISSUE TITLE
Many paredit commands break with multiple selections

### ISSUE THREAD

**Issue by StarScape** [BetterThanTomorrow/calva#732] opened 2020-08-06 00:08 UTC
For example, trying to do a slurp here: 

![image](https://user-images.githubusercontent.com/4681820/89475947-5d8efd00-d757-11ea-9b5b-2891654c296a.png)

Will only slurp on the top line.

**Comment by PEZ** [comment] 2020-08-06 07:32
Thanks for reporting! However I am going to close this as it is a duplicate of #610 .

**Closed by PEZ** 2020-08-06 07:32 UTC

**Comment by StarScape** [comment] 2020-08-06 12:47
Ah, I should have looked first :)

**Comment by PEZ** [comment] 2020-08-06 13:09
No worries. Please upvote/chime in on that other issue. This should be within reach to fix, but I haven't experimented with it so there are probably dragons.

**Comment by StarScape** [comment] 2020-08-06 16:04
Odd to me it does not work out of the box for all cursors...but I know nothing about the VSCode API. I might take a look myself if I can ever find the time, but you know how that goes.
