### ISSUE TITLE
Rainbow parens/brackets highlight is lost when scrolling non-active editor

### ISSUE THREAD

**Issue by filipesilva** [BetterThanTomorrow/calva#565] opened 2020-02-24 12:53 UTC
When using more than one editor, and scrolling without selecting the editor, the rainbow highlight for parens/brackets is lost.

You can see this happening by:
- opening two editors side by side with several screens worth of code in them
- selecting the first
- scrolling the second without selecting it

You highlight for parens/brackets is not present for off-screen sections:
![image](https://user-images.githubusercontent.com/4172079/75153996-9cc71580-5704-11ea-93d7-85d67203dcce.png)

Once you click the editor, thus selecting it, rainbow highlighting is back:
![image](https://user-images.githubusercontent.com/4172079/75154029-a9e40480-5704-11ea-9091-e3fd49ea6dbf.png)

**Comment by bpringe** [comment] 2020-05-12 19:31
The intention is to only apply bracket highlighting for the active editor and for only sections in the view port. @PEZ, this was done for performance reasons right? Would we want to keep it this way?

**Comment by bpringe** [comment] 2020-11-30 21:52
Closing this since it works as intended, but please re-open if needed.

**Closed by bpringe** 2020-11-30 21:52 UTC
Labels: under discussion
