### ISSUE TITLE
evaluating a def form in cljs repl prints the result in a vector (shadow-cljs)

### ISSUE THREAD

**Issue by fel-mazo** [BetterThanTomorrow/calva#2228] opened 2023-06-21 13:18 UTC
this is probably coming from shadow-cljs.

here is an example:

`(def test {})
-> [{}]
`

**Comment by PEZ** [comment] 2023-06-21 20:03
It's happening also without Calva in the picture. I haven't figured out in which version of shadow-cljs it started to happen. So far I have:

* 2.19.9: `(def a 1) => #'cljs.user/a`
* 2.23.3: `(def a 1) => [1]`

Reproduce with a shadow-cljs project with an `:app` build:

```clojure
❯ clj
Clojure 1.11.1
user=> (do (require (quote shadow.cljs.devtools.server)) (shadow.cljs.devtools.server/start!) (require (quote shadow.cljs.devtools.api)) (shadow.cljs.devtools.api/watch :app)
...
[:app] Compiling ...
[:app] Build completed. (170 files, 169 compiled, 0 warnings, 6.93s)
:watching
```

Start the app

```clojure
user=> (do (require 'shadow.cljs.devtools.api) (shadow.cljs.devtools.api/repl :app))
cljs.user=> (def foo 1)
[1]
cljs.user=>
```

**Comment by PEZ** [comment] 2023-06-22 06:44
It starts happening in [shadow-cljs 2.21.0](https://github.com/thheller/shadow-cljs/blob/master/CHANGELOG.md#2210---2023-02-19).

**Comment by PEZ** [comment] 2023-06-23 10:46
Closing this, because there is nothing (sane) Calva can do about it.

**Closed as completed by PEZ** 2023-06-23 10:46 UTC
Labels: upstream, evaluation, cljs
