### ISSUE TITLE
[REPL Window] undefined namespace when starting a shadow-cljs cljs REPL Window

### ISSUE THREAD

**Issue by PEZ** [BetterThanTomorrow/calva#115] opened 2019-02-04 08:43 UTC
This is using the preview of the coming Calva with that spiffy REPL Window:

Opening a ClojureScript REPL in a shadow-cljs project (Calva itself as it happens) the prompt displays:
```
undefined=>
```
I don't have the time right now to investigate it further, not even if the namespace really is undefined 😄, so just dumping the bug report here.

**Comment by cfehse** [comment] 2019-10-15 14:20
This is fixed in version 2.0.49.

**Comment by cfehse** [comment] 2019-10-16 06:42
This was not fixed in version 2.0.49!

The root cause for the problem is that the cljs repl is connected but no application is connected. In this situation the code:

```
let res = this.session.eval("nil");
await res.value;
```
The returned promise contains literally nothing and the resulting `res.ns` is undefined.

I tested this issue with the calva cljs-lib - and I have no idea how to "connect an application to the REPL" for that project.

**Comment by PEZ** [comment] 2019-10-16 06:46
You press F5 :smile:

It's mentioned here: https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute

**Comment by PEZ** [comment] 2019-10-16 06:50
It is not much we can do about ”no prompt when no app”, but we could, maybe, detect the situation. I have tried many times, and failed. That is not to say it is not possible. I had a chat with Thomas Heller about this some months ago, and he mentioned a message bus that shadow-cljs has, that could probably be used to make Calva know what state the connection is in.

**Comment by cfehse** [comment] 2019-10-16 06:51
> You press F5 😄

That's a problem: you cannot run the debug instance in the directory you are debugging from - at least not on Windows. So I made a copy of calva in ran the debugged calva there. This will not start the clsj-lib.

**Comment by cfehse** [comment] 2019-10-16 06:56
> It is not much we can do about ”no prompt when no app”, but we could, maybe, detect the situation. I have tried many times, and failed. That is not to say it is not possible. I had a chat with Thomas Heller about this some months ago, and he mentioned a message bus that shadow-cljs has, that could probably be used to make Calva know what state the connection is in.

Unfortunately shadow-cljs simply returns nothing instead of an error.

**Closed** 2019-10-24 20:57 UTC
Labels: repl-window
