### ISSUE TITLE
Action "watch" requires one or more build ids - shadow-cljs jack-in

### ISSUE THREAD

**Issue by milahu** [BetterThanTomorrow/calva#2014] opened 2023-01-09 17:24 UTC
im trying to run https://github.com/fulcrologic/fulcro-template

so i do `jack-in` &rarr; `shadow-cljs` &rarr; `:main`

output.calva-repl:

```clj
; Jacking in...
; Starting Jack-in Terminal: npx shadow-cljs -d cider/cider-nrepl:0.28.5 watch
```

terminal:

```
npx shadow-cljs -d cider/cider-nrepl:0.28.5 watch
shadow-cljs - config: shadow-cljs.edn
shadow-cljs - starting via "clojure"

Action "watch" requires one or more build ids
```

so the command should be `watch main` or `watch :main`

```
npx shadow-cljs -d cider/cider-nrepl:0.28.5 watch main 
shadow-cljs - config: /home/user/src/milahu/reuploader/fulcro/fulcro-template/shadow-cljs.edn
shadow-cljs - starting via "clojure"
shadow-cljs - HTTP server available at http://localhost:8022
shadow-cljs - HTTP server available at http://localhost:8023
shadow-cljs - server version: 2.16.12 running at http://localhost:9630
shadow-cljs - nREPL server started on port 9000
shadow-cljs - watching build :main
[:main] Configuring build.
[:main] Compiling ...
GUARDRAILS IS ENABLED. RUNTIME PERFORMANCE WILL BE AFFECTED.
Mode: :runtime  Async? false  Throw? false
Guardrails was enabled because the CLJS Compiler config enabled it
```

**Comment by MorKaragh** [comment] 2023-01-14 16:02
Same problem. Please, add fix.

**Comment by PEZ** [comment] 2023-01-15 11:27
I can't reproduce this. Please note that the start builds menu is multi-select. You have to tick the checkbox. Did you do that?

<img width="621" alt="image" src="https://user-images.githubusercontent.com/30010/212537854-5292cc15-55b3-457f-931e-e84f5d1a0880.png">

**Comment by milahu** [comment] 2023-01-15 13:57
> Please note that the start builds menu is multi-select. You have to tick the checkbox.

yes, that was the problem.
i was using `up`/`down` + `enter`
but i should use `up`/`down` + `space` + `enter`

can we make the jack-in fail early in this case?
ie, print something like "please select at least one build-target"

**Comment by bpringe** [comment] 2023-01-15 22:25
@milahu That sounds like a good idea. A PR is welcome. I created [a new issue](https://github.com/BetterThanTomorrow/calva/issues/2022) related to your comment and will close this one. This issue should help anyone searching for this issue in the meantime.

**Closed as completed by bpringe** 2023-01-15 22:25 UTC
