### ISSUE TITLE
Slurping anonymous function shorthand causes invalid syntax

### ISSUE THREAD

**Issue by bpringe** [BetterThanTomorrow/calva#883] opened 2020-12-22 00:35 UTC
Just came across this randomly and wanted to record it before it gets lost in the void. In the gif below, I type `(.then)` and then hit the shortcut for slurp sexp forward (and that's it). You can see the `#` stays next to `.then` and the cursor for some reason jumps backwards out of the list.

![slurp-function-shorthand](https://user-images.githubusercontent.com/12722744/102834941-33f30d00-43aa-11eb-8757-fed26c523ef3.gif)

**Comment by PEZ** [comment] 2020-12-22 07:43
Good recording. Looks like it could be a more general root cause there, but my brain hasn't started yet, so can't really grasp it.

**Comment by PEZ** [comment] 2021-01-04 09:21
I have a request for you, @bpringe . 😄 These images and gifs are very good for showing what is going on. To go with them I want to have the text as well. It's easy to get it wrong when retyping it.

Anyway, I just tried this. It is the formatting that is causing the invalid syntax. Or, rather, it is at the formatting step that this happens. Like so:

0. The cursor is at the end of the list before the anon fn: `(foo|)#()`
1.  *Slurp forward* moves the closing paren to the right of the anon fn: `(foo|#())`
2. The formatting sees a list with the symbol `foo#` followed by a list and formats it, adding whitespace: `(foo# ())`

Not sure where the cursor displacements happen, doing thie formatting step in isolation doesn't provoke it. But it seems it happens after the formatting, because the enclosing list does not get formatted when slurping. If we check what it is the formatter gets as input we might be able to pinpoint this.

Not sure what the fix is here. Maybe adding a space where the opening paren were as part of the slurp...

**Comment by bpringe** [comment] 2021-01-04 16:33
I'll try to remember to provide the text next time :smile:

> Maybe adding a space where the opening paren were as part of the slurp...

I think this would actually make sense. Without having thought about it much, it seems like in any case, if slurp is performed and the thing immediately before the cursor is _not_ an open/close token (and maybe some other things?), then a space can/should be placed there.

* `[|]1` - no space should be placed before the cursor because the token before it is `[`
* `[1]2` - a space should be placed before the cursor because the token before it is `1`

These are just a couple of examples to demonstrate. We'd need to spend some time thinking about other cases.

**Comment by bpringe** [comment] 2021-01-04 16:35
And also the same thing for slurping the other way, of course.

**Comment by PEZ** [comment] 2021-01-04 16:50
Since we format after the slurp we can probably add the space unconditionally and rely on the formatter to clean up extraneous whitespace.

**Comment by PEZ** [comment] 2021-01-04 17:22
Seems I was not completely right about that...

![creeper](https://user-images.githubusercontent.com/30010/103561316-93c4da00-4eb9-11eb-9757-c3bd667376d6.gif)

**Comment by bpringe** [comment] 2021-01-04 19:35
Is this something to be fixed in the formatter? I mean should the formatter remove extra spaces in that situation?

**Comment by PEZ** [comment] 2021-01-04 20:29
It is that we use `on-type` formatting  options here. I don't think we should, but I am not sure. Will cook a PR that we can test a bit and see if it behaves.

**Comment by PEZ** [comment] 2021-01-04 20:30
`on-type` formatting does not trim surrounding whitespace. Maybe that wasn't clear in my previous comment...

**Closed** 2021-01-07 18:56 UTC
Labels: bug, paredit
