### ISSUE TITLE
"Go to definition" does not work correctly with symlinks

### ISSUE THREAD

**Issue by otwieracz** [BetterThanTomorrow/calva#611] opened 2020-04-13 08:57 UTC
On `Ubuntu-18.04` in WSL:

1. Open `~/Work/.../...` folder in VSCode. `:
```
~/Work -> /mnt/c/Users/Slawek/Work/
/mnt/c -> /c/

$ realpath ~/Work
/c/Users/Slawek/Work
```
2. Have `src/clj/.../api.clj` file opened:
![Annotation 2020-04-13 104701](https://user-images.githubusercontent.com/108072/79107141-22198e80-7d74-11ea-831d-f782215dbe08.png)
3. In `foo.api` namespace, click "Go to definition" on `(upload-handler ...)`
![Annotation 2020-04-13 104607](https://user-images.githubusercontent.com/108072/79107078-01e9cf80-7d74-11ea-8deb-6f1bcb2ea72a.png)
4. Target file is opened via it's absolute path as a new file, although the same file is already openen relative to project:
![Annotation 2020-04-13 105021](https://user-images.githubusercontent.com/108072/79107398-96ecc880-7d74-11ea-85f3-9f3f272e087c.png)
(Some names were redacted)

After adding my project folder via it's absolute path `/c/Users/...` "Go to definition" behaves correctly.

**Comment by bpringe** [comment] 2020-12-23 23:49
This may work after #572 is released, which should be soon.

**Comment by PEZ** [comment] 2023-12-19 11:47
I can't reproduce this, with or without clojure-lsp. Is it still an issue for you, @otwieracz?

**Comment by otwieracz** [comment] 2023-12-20 06:53
Unfortunately I no longer have an environment with WSL, so won't be able to reproduce.

**Comment by bpringe** [comment] 2024-01-01 01:32
Going to close this, but if anyone finds it and has the same problem in the future, feel free to comment here and we can reopen it.

**Closed by bpringe** 2024-01-01 01:32 UTC
Labels: bug
