### ISSUE TITLE
[REPL Mac] cmd+c cmd+v not working

### ISSUE THREAD

**Issue by claynon** [BetterThanTomorrow/calva#119] opened 2019-02-05 09:48 UTC
I can't paste on the repl window nor copy from the repl window
Some other problems related to writing on the repl:
 - sometimes I can't write the character `'`
 - I can't use some diacritcs: [`â` `á` `ã`]  are printed as [`^a` `'a` `~a`] 
 - can't erase the character `)`. The only way to solve it (that I know) is sending the unbalanced code for eval. You can get unbanlaced parenthesis when pressing backspace twice in the following scenario:
```
(|:a) =>  |:a)
```

```
System versions:
macOS Mojave 10.14.2
VSCode 1.30.2
Calva 1.3.62-SNAPSHOT
```

**Comment by mseddon** [comment] 2019-02-05 11:36
To force-delete an unbalanced parenthesis you can use `alt+delete` or `alt+backspace`, but the paredit should not get you into that position from your reproduction, so definitely a bug, thanks!

The clipboard issue is definitely already on the radar, and I think I understand what is happening there.

I am not sure about the diacritics- what keyboard layout do you have? how do you type them on your keyboard (what combination of letters+modifiers?, and do you use multiple keystrokes to type them?).

**Comment by mseddon** [comment] 2019-02-05 12:01
Accidentally deleting the opening paren is my paredit logic looking *behind* the start of the buffer and getting confused. Need an 'all or nothing' getRange for the local parenthesis checks to ensure it's looking at a correctly sized string.

**Comment by mseddon** [comment] 2019-02-05 12:03
Diacritics paste correctly into the repl in the dev branch (where clipboard works again)- so it seems that it's not a font issue at least. I wonder if it's a combining input event.

**Comment by claynon** [comment] 2019-02-05 12:14
My keyboard is `U.S. International - PC`

To do diacritics I type `'` followed (after I release the key) by `a`

This diacritic issue does not affect me, but I thought it would be helpful to know this behavior exists

The thing that I couldn't duplicate exactly is the first bullet point (regarding `'`). It works sometimes and other times it doesn't. From what I noticed when it stops working it only works when I restart VSCode

**Comment by claynon** [comment] 2019-02-05 12:54
Yes, writing `'atom` is producing `'atom` on the repl
everywhere else in my computer it produces `átom`

for `'` I do not use any modifying key (for `^` I use `shift+6` and for `~` I use `` shift+` ``)

**Comment by claynon** [comment] 2019-02-06 16:23
I manage to replicate the problem that I was having:

copy and pasting (so does writing `'`) is working in general
but it stops working when I hit `ctrl+g`, after that I need to restart my VSCode to make it go back to working
the `'` stoping to work is a bit worse than the copying and pasting, because it gets impossible to write symbols (like `'foo`)

**Comment by PEZ** [comment] 2019-02-07 10:54
Is `ctrl+g` bound to *Goto Line* in your setup?

**Comment by claynon** [comment] 2019-02-07 10:58
In the repl window yes. In the rest of VSCode no.
I use emacs keybinding, but on the repl window it ignores this emacs extension, which is a problem for me.
I usually hit `ctrl+g` because it means `cancel` in emacs keybinding, and hit it without noticing sometimes.

**Comment by PEZ** [comment] 2019-02-07 11:44
I see. I have similar behavior with the ESC key from my many `vi` days. :smile:

On my keyboard (Swedish) the `'` is not a ”dead” key (a term I use for a key that waits with producing the final result until it is determined if it should modify the following character typed). So I don't end up with not being able to type quoted symbols like `'foo`.

However, to type `á` I would press a key that is a ”dead” key with the symbol `´` on it, then `a`. And to type `à` I use the same key modified by `shift` for the symbol ``` (aka backtick). And even if I can't reproduce the `ctrl+g` thing, I can't type these ”dead” key combinations in the REPL window.

(Please file the emacs key binding thing as a separate issue, I don't know what can be done about it, but I really would like to track it on its own merits.)

**Comment by PEZ** [comment] 2019-06-07 08:59
Is this still an issue?

**Comment by cfehse** [comment] 2019-10-15 06:12
I am closing this issue for now. Feel free to reopen it if the problem still exists.

**Closed by cfehse** 2019-10-15 06:12 UTC
Labels: bug, repl-window
