### ISSUE TITLE
Project clj-kondo config file not being considered

### ISSUE THREAD

**Issue by lread** [BetterThanTomorrow/calva#1026] opened 2021-02-09 20:06 UTC
**Symptom**
When I run clj-kondo from the command line I get no errors and no warnings.
In Calva, clj-kondo issues are reported.

**Enviromnent**
- Calva v2.0.170
- clj-kondo v2021.01.20
- macOS 10.15.7
- clojure v1.10.2.77

**Reproduction**
1. Clone my project's v1 branch (I'll refine this to something smaller if its too much)
    ```Shell
    $ git clone --branch v1 https://github.com/clj-commons/rewrite-clj.git rewrite-clj-repro
    ```

    If you want to match the exact commit I tested against:
    ```Shell
    $ cd rewrite-clj-repro
    $ git reset --hard 377bb5d7f86a4751350b0d347856b60a25528bc4
    $ git clean -f -d
    ```
2. Run clj-kondo on the command line and witness no errors/warnings:
    ```Shell
    $ cd rewrite-clj-repro
    $ clj-kondo --lint src test script
    linting took 1287ms, errors: 0, warnings: 0
    ```
3. Open the cloned repo in Calva and navigate to `test/rewrite_clj/zip_test.cljc`

**Expected Behaviour**
I would expect to see no clj-kondo errors, matching the command line invoked clj-kondo results.

**Actual Behaviour**
I see unresolved-var clj-kondo warnings, for example:
![image](https://user-images.githubusercontent.com/967328/107415365-47d10a80-6ae1-11eb-9ac0-b67ca3ef0cf3.png)

**Extra Info**
1. On Slack I was talking about clj-kondo hooks, you should ignore that.
2. I am new to Calva, maybe I missed something obvious?
2. I already just fixed one typo in my `.clj-kondo/config.edn` maybe there's something else amiss in there that clj-kondo handles just fine but affects Calva.
3. If I delete the [`:lint-as` config for `import-vars`](https://github.com/clj-commons/rewrite-clj/blob/377bb5d7f86a4751350b0d347856b60a25528bc4/.clj-kondo/config.edn#L21-L22)and rerun clj-kondo from the command line, as expected, tons of unresolved symbol errors are reported from clj-kondo command-line.

**Comment by bpringe** [comment] 2021-02-09 20:50
Thanks for the detailed report. @ericdallo, since Calva's really just the middleman here, I think this would be more something with clojure-lsp itself. Calva doesn't affect what clojure-lsp uses as the clj-kondo config or how files are linted.

**Comment by ericdallo** [comment] 2021-02-09 21:00
I will test it locally soon with only clojure-lsp + emacs

**Comment by ericdallo** [comment] 2021-02-09 21:51
@lread I found the issue, it is a [clj-kondo issue](https://github.com/clj-kondo/clj-kondo/issues/1143) that happens with libs that use `potemkim` like `rewrite-clj`, so clj-kondo does not return analysis for those symbols 😔 It's actually the same issue we run using clojure-lsp on its own project 😅 , that's why we have [these config](https://github.com/clojure-lsp/clojure-lsp/blob/master/.clj-kondo/config.edn#L1-L3)
c/c @borkdude

**Comment by borkdude** [comment] 2021-02-09 22:17
The question remains why clj-kondo itself gives no warnings for @lread's project but clojure-lsp does? 

@lread has these hooks:

```
 :hooks {:analyze-call {rewrite-clj.potemkin.clojure/import-vars-with-mods
                        hooks.rewrite-clj.potemkin.import-vars-with-mods/import-vars-with-mods

                        rewrite-clj.potemkin.cljs/import-vars-with-mods
                        hooks.rewrite-clj.potemkin.import-vars-with-mods/import-vars-with-mods}}
```

which are used to "teach" clj-kondo how to interpret their custom import-vars macros. It seems this isn't recognized by the clj-kondo invocation of clojure-lsp.

**Comment by borkdude** [comment] 2021-02-09 22:28
I checked the referenced issue and that turned out to be a non-issue.

**Comment by ericdallo** [comment] 2021-02-09 22:46
Got it, didn't notice that, I will double-check clojure-lsp so

**Comment by ericdallo** [comment] 2021-02-09 23:00
Testing local I confirmed clojure-lsp is not considering the project clj-kondo config file for some reason, I'll take a look, created this issue to track: https://github.com/clojure-lsp/clojure-lsp/issues/308

**Comment by ericdallo** [comment] 2021-02-10 03:06
Fixed on latest clojure-lsp release, it seems it was a bug introduced during the kondo integration, I'll think in some kind of integration test to catch bugs like that.

@lread after Calva updates clojure-lsp version, you should get no warnings in your project again :)

**Closed as completed** 2021-02-10 17:18 UTC
Labels: lsp

**Comment by bpringe** [comment] 2021-02-10 18:20
@lread Please try out the latest version and see if the issue is resolved. (2.0.171)

**Comment by lread** [comment] 2021-02-10 18:51
Much thanks for the fix, I am no longer getting unresolved-var errors in Calva v2.0.171 for my `import-var`ed variables.

But... something else seems amiss now.  If you look up at my original example screenshot code snippit from this issue:
```Clojure
(deftest of-string-simple-sexpr
  (let [sexpr "(+ 1 2)"]
   (is (= sexpr (-> sexpr z/of-string z/root-string)))))
```

It's good, no unresolved-var errors.  But.. if I add in something obviously invalid:
```Clojure
(deftest of-string-simple-sexpr
  (let [sexpr "(+ 1 2)"]
   (is (= sexpr (-> sexpr z/of-string z/invalid z/root-string)))))
```
I would expect an unresolved-var error for `z/invalid` but am not seeing it reported in Calva.

If I run clj-kondo from the command line, I get the expected warning:
```Shell
$ clj-kondo --lint src test script
test/rewrite_clj/zip_test.cljc:10:39: warning: Unresolved var: z/invalid
linting took 1395ms, errors: 0, warnings: 1 
```

If I temporarily add in something contrived like:
```Clojure
(string/notgood)
```
Calva correctly reports the clj-kondo unresolved-var warning.

Do you see this as unexpected behaviour? If so, do you want me to raise a separate issue?

**Comment by bpringe** [comment] 2021-02-10 18:54
Hmm @ericdallo ^?

**Comment by ericdallo** [comment] 2021-02-10 19:07
Yeah, I confirmed this is happening in clojure-lsp with lsp-mode too.
But with my tests, clj-kondo is not returning the unresolved-var too 🤔  when adding a `z/unknown-function`:
```clojure
$ cat ./rewrite-clj-repro/test/rewrite_clj/zip_test.cljc | clj-kondo --config '{:cache false}' --lint -
=> linting took 201ms, errors: 0, warnings: 0
```
Am I missing something @borkdude ?

**Comment by borkdude** [comment] 2021-02-10 19:12
@ericdallo Clj-kondo will only complain about unresolved vars when you lint both namespaces at the same time, or one the required namespaces comes from the cache.

**Comment by lread** [comment] 2021-02-10 19:14
There's probably a good reason Calva/lsp is not using clj-kondo cache?

**Comment by ericdallo** [comment] 2021-02-10 19:19
oh, got it, I changed clojure-lsp to not use the cache when linting a single file, so that is not fixed correctly, I could not make it work without not using the cache though, I'll need to understand why adding the cache make clj-kondo ignore the config

**Comment by borkdude** [comment] 2021-02-10 19:20
Yeah, that's not so beneficial since clj-kondo won't get updated information while the user is typing.

**Comment by ericdallo** [comment] 2021-02-10 19:33
@borkdude do you see any config that does not makes sense [here](https://github.com/clojure-lsp/clojure-lsp/blob/master/src/clojure_lsp/config.clj#L6-L23),  besides the `cache false`?

**Comment by borkdude** [comment] 2021-02-10 19:37
@ericdallo nope, makes sense

**Comment by ericdallo** [comment] 2021-02-10 20:47
So as discussed [here](https://clojurians.slack.com/archives/CBE668G4R/p1612987531306800?thread_ts=1612926799.297900&cid=CBE668G4R) this is a corner case [bug on clj-kondo](https://github.com/clj-kondo/clj-kondo/issues/1167), I'll fix clojure-lsp side to always use the cache thought, but we still need a fix on clj-kondo @lread

**Comment by lread** [comment] 2021-02-10 20:49
Coolio, thanks for update! Nice troubleshooting!
