### ISSUE TITLE
Running the contributed command:'calva.evaluateSelection' failed.

### ISSUE THREAD

**Issue by micahasmith** [BetterThanTomorrow/calva#46] opened 2018-06-07 21:27 UTC
I tried uninstalling/reinstalling, but its not working. The strange thing is, it was working, and then upon closing and reopening code, starting and entering the new repl, it stopped working.

Any way to troubleshoot the exception when this happens?

I am using 1.24.0.

Thanks--

**Comment by micahasmith** [comment] 2018-06-07 21:42
Also, strange to note that the problems tab is still accurately showing passing/failing tests.

**Comment by PEZ** [comment] 2018-06-08 07:10
Do the tests still run? That does sound strange.

Troubleshooting this is not easy. You can check for error in the console in vscode's developer tools, but chances are it just says ”an error occurred”. Another way is to fork this repo and follow the [How to Contribute](https://github.com/BetterThanTomorrow/calva/wiki/How-to-Contribute) steps and try see if you can catch the point of error with a breakpoint. (This is a bit harder than it should be because the source maps are not good enough, but sometimes it works).

Before you go through that trouble, though, have you tried with another project? Something really simple.

**Comment by sebn** [comment] 2018-06-10 14:16
Hello there,

I'm using a custom keyboard shortcut to run the `calva.evaluateSelection` command.
When I use the shortcut in the editor, it fails with message *Running the contributed command:'calva.evaluateSelection' failed.*

What is weird is that when I open the command palette and select the *Calva : Evaluate selection or current form* command (the one with the same custom shortcut visible on the right), it actually works.

@micahasmith Do you get the same behavior on your side?

**Comment by micahasmith** [comment] 2018-06-11 13:16
wow. exactly the same as what @sebn reported. it works through the cmd+p but not through the shortcut anymore

**Comment by micahasmith** [comment] 2018-06-11 17:55
i tried remapping the shortcut to see if that would fix it... no dice

also strange-- the mappings for evaluate current selection in repl still works

**Comment by PEZ** [comment] 2018-06-11 18:48
The strangeness is strong in this bug. But at least we now have some more clues. 🤠

**Comment by PEZ** [comment] 2018-06-11 20:01
I got this now! Using VS Code Insiders. Is that what you guys are using too?

**Comment by micahasmith** [comment] 2018-06-11 20:37
i'm on 1.24.0

**Comment by micahasmith** [comment] 2018-06-12 13:37
10.13.4 high sierra as well

**Comment by sebn** [comment] 2018-06-12 19:43
VSCode 1.24.0 + macOS 10.13.4 here as well.

**Comment by sebn** [comment] 2018-06-13 07:22
Also I can confirm that:

- It works with VSCode 1.23.x
- I get the exact same issue with VSCode 1.24.0 on Fedora 28 (I can find the time to test on Windows 10 if it may help, but it doesn't really look like an OS specific issue)

**Comment by PEZ** [comment] 2018-06-18 08:36
Without understanding why this happens, I have patched Calva to dodge the problem. Please update the extension and let me know if things have started to work again for you. (Seems to work for me)

**Comment by micahasmith** [comment] 2018-06-18 12:29
@PEZ fixed for me on VSCode 1.24.1 MacOS 10.13.4. thank you!

**Comment by PEZ** [comment] 2018-06-18 21:39
Thanks for letting me know! Closing this now.

**Closed by PEZ** 2018-06-18 21:39 UTC

**Comment by sebn** [comment] 2018-07-03 08:07
(sorry for the late answer, I couldn't find the time to test again until now)

I can confirm everything works fine for me too. Thanks @PEZ :)
