### ISSUE TITLE
repl toooooo slow when throw exceptoin

### ISSUE THREAD

**Issue by paomian** [BetterThanTomorrow/calva#1051] opened 2021-03-03 09:39 UTC
1. jack-in
2. eval `(/ 1 0)` in repl

I test in a few projects.but the result is same.I don't know what happen.Is it wrong of my config ?

```json
    "calva.prettyPrintingOptions": {
    
        "enabled": true,
        "printEngine": "pprint",
        "width": 120,
        "maxLength": 50
    },
    "calva.paredit.defaultKeyMap": "original",
    "calva.highlight.rainbowIndentGuides": true,
    "[clojure]": {
        "editor.wordSeparators": "\t ()\"':,;~@#$%^&{}[]`",
        "editor.autoClosingBrackets": "always",
        "editor.autoClosingQuotes": "always",
        "editor.formatOnType": true,
        "editor.autoIndent": "full",
        "editor.formatOnPaste": true,
        "files.trimTrailingWhitespace": false,
        "editor.matchBrackets": "never",
        "editor.renderIndentGuides": false,
        "editor.parameterHints.enabled": false
    },
    "calva.jackInEnv": {
        "JVM_OPTS": "${env:JVM_OPTS} -Darchaius.configurationSource.defaultFileName=paomianl_config.properties -Dorg.quartz.properties=quartz.properties"
    }
```

**Comment by paomian** [comment] 2021-03-03 11:40
maybe it is same reason?
https://github.com/BetterThanTomorrow/calva/issues/929
the start params is `lein update-in :dependencies conj '[nrepl,"0.8.3"]' -- update-in :plugins conj '[cider/cider-nrepl,"0.25.8"]' -- update-in '[:repl-options,:nrepl-middleware]' conj '["cider.nrepl/cider-middleware"]' -- repl :headless`

**Comment by PEZ** [comment] 2021-03-03 12:13
The only thing I can suspect is that it is something with your `jackInEnv`. Try without it and see if that makes a difference?

**Comment by paomian** [comment] 2021-03-03 12:52
I commented out my JVM_OPTS still not working.

-----------
and my refresh all namespace is broken too.
when I run refresh all namespace It returns the result below.can't reload anything.

```
Reloading all the things...
Reloaded: ()
:ok
```

**Comment by PEZ** [comment] 2021-03-03 17:48
Sounds like a separate issue, but also it looks to be working from that message.

So if you make a fresh project, using `lein new`, and no `jackInEnv`, you still have a slowness with the exceptions?

**Comment by bpringe** [comment] 2021-03-03 18:07
It does sound like the problem noted here: https://github.com/BetterThanTomorrow/calva/issues/929#issuecomment-754804875

Try looking at your classpath as noted there and checking the versions of cider-nrepl and orchard. With lein, the versions in the jack-in command are not necessarily the versions used, unfortunately. You may want to comment out / remove things in your lein user profile as well to see if that helps.

**Comment by paomian** [comment] 2021-03-05 04:13
> So if you make a fresh project, using lein new, and no jackInEnv, you still have a slowness with the exceptions?

@PEZ  I create a new project.and jackin it is quickly when throw exception.but How to know where the time is spent?I have no idea.
> Try looking at your classpath as noted there and checking the versions of cider-nrepl and orchard. With lein, the versions in the jack-in command are not necessarily the versions used, unfortunately. You may want to comment out / remove things in your lein user profile as well to see if that helps.

@bpringe  I run deps command with this command

```
lein update-in :dependencies conj '[nrepl,"0.8.3"]' -- update-in :plugins conj '[cider/cider-nrepl,"0.25.8"]' -- update-in '[:repl-options,:nrepl-middleware]' conj '["cider.nrepl/cider-middleware"]' -- with-profile +dev deps :tree
```
got the version  [cider/cider-nrepl "0.25.8"] 
but i can't get orchard in my deps.


--------------------
> refresh all namespace is broken too.

Sorry.My bad.Do not discuss this issue in this issue.It makes this issue messy.

**Comment by PEZ** [comment] 2021-03-05 16:38
You probably have some nrepl or cider-nrepl dependencies in your projects. Remove those, and you should be good.

**Comment by bpringe** [comment] 2021-03-05 17:35
>  I run deps command with this command

The version you see in that jack-in command is not necessarily the version being used. Sorry if I wasn't clear. Running `lein classpath` from the project directory should show you the versions being used for that project. 

This won't fix anything, though, of course. There is likely a dependency in your `~/.lein/profiles.clj` that's causing an issue. Try commenting out that file or removing it, or removing things from it one by one until you find what it is. If you see `nrepl` or `cider-nrepl` there, that is likely the culprit. Otherwise, it could be something else that depends on those.

**Comment by alidcast** [comment] 2022-07-12 19:31
@bpringe  If we're starting our own repl and then connecting to Calva, what. version should we be using? 

I always wondered how people put up with such lag when errors occurred, never expected it to be due to local deps 😆

**Comment by alidcast** [comment] 2022-07-12 19:40
upgrading cider nrepl deps to same ones calva jack-in prints out fixed issue! omg what a relief 😅

**Comment by bpringe** [comment] 2022-07-16 01:12
> If we're starting our own repl and then connecting to Calva, what. version should we be using?

@aleedmanath Just FYI, and for anyone else reading this later, you can find this info in the Calva says output channel. You can also get the command used by jack-in by running the "Calva: Copy Jack-in Command to Clipboard" command.

**Comment by bpringe** [comment] 2022-07-16 01:13
I'm going to close this issue since it seems it was caused by a dependency. @paomian Please feel free to reopen if you're still having issues and don't think it's a dep issue.

**Closed as completed by bpringe** 2022-07-16 01:13 UTC
