### ISSUE TITLE
`Wrap` is not respected when an expr result has a long output

### ISSUE THREAD

**Issue by pinkfrog9** [BetterThanTomorrow/calva#1729] opened 2022-05-16 00:47 UTC
It seems Calva breaks the disable wordwrap option in vscode. After I evaluate some code that has a long output, line is not wrapped, even the setting in vscode is `wrap on`.

**Comment by PEZ** [comment] 2022-05-16 05:03
This seems to be an issue with VS Code, rather than with Calva. But we can probably mitigate it by truncating long inline results.

**Comment by PEZ** [comment] 2022-05-16 06:11
I can't reproduce this.

In this screenshot line wrap stays on, even though the result is very long:

<img width="778" alt="image" src="https://user-images.githubusercontent.com/30010/168529913-e49188f4-82f2-4748-8b7c-48b17c3ba15b.png">

Can you give some more detail, @introom?

**Comment by pinkfrog9** [comment] 2022-05-16 06:14
Try this:
```
(ns task.test
  (:require
   [clojure.string :as str]))


(str/join "" (repeat 100 "asfdsf"))

```

**Comment by PEZ** [comment] 2022-05-16 06:23
Same. 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/30010/168531443-26015849-ab0d-4151-bd1b-4859a3a21b58.png">

This will get much easier if you tell us what you expect to happen and how the result differs from that. Right now I might be reproducing the problem without realizing it.

**Comment by pinkfrog9** [comment] 2022-05-16 06:26
Before evaluating,  the horizontal scrolling bar does not appear (since wrap is set to be on).
<img width="921" alt="image" src="https://user-images.githubusercontent.com/669045/168531719-8dc2d83e-6aa4-442c-8d0f-274190ef3748.png">


After evaluating `(str/join "" (repeat 100 "asfdsf"))`, the bar occurs
<img width="912" alt="image" src="https://user-images.githubusercontent.com/669045/168531784-4dcf093f-2ad4-4d1c-8a89-02548a4343bc.png">

**Comment by PEZ** [comment] 2022-05-16 06:40
OK. Yes, that's the way these decorators work. They add to the width off the document, even after they are dismissed. The best you can do is to make another file the active one and go back.

Going to close this, because it is not really actionable. I suggest you check if it has been reported on VS Code, and otherwise report it. Would surprise me if it isn't reported, since it has been like this for very long.

**Closed as completed by PEZ** 2022-05-16 06:40 UTC
Labels: upstream

**Comment by pinkfrog9** [comment] 2022-05-16 07:00
Yes. The `decorator` is the keyword here.
https://github.com/microsoft/vscode/issues/32856

**Comment by PEZ** [comment] 2022-05-16 09:58
Thanks for sharing that!
